title: Nabil Elqatib's blog
name: Nabil Elqatib
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-midnight

exclude:
  - .editorconfig
  - .git
  - .gitignore
  - .sass-cache/
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

twitter:
    username: neqneqneq
    card: summary

google_analytics: G-6F7Q8R73G5

tag_page: '/blog/tags.html'

social:
  github: https://github.com/n-eq
  linkedin: https://linkedin.com/in/nabilelqatib
  rss_feed: 'feed.xml'

# jekyll paginate settings
paginate: 8
paginate_path: "/blog/page:num/"
